callTypeAST = 'Call'
equals = 'Eq()'
floatTypePython = 'float'
funcNamesNotToTest = ['__init__', 'visit_FunctionDef']
groupTypes = ['G1', 'G2', 'GT', 'ZR']
hashType = 'hash'
hashTypesCharm = ['hash', 'H', 'H2']
intTypePython = 'int'
left = 'left'
listTypePython = 'list'
numTypeAST = 'Num'
right = 'right'
strTypeAST = ['Name', 'Str']
strTypePython = 'str'
tupleAST = 'elts'
verifyFuncName = 'verify'
