equals = 'Eq()'
floatTypePython = 'float'
funcNamesNotToTest = ['__init__', 'visit_FunctionDef']
intTypePython = 'int'
left = 'left'
numTypeAST = 'n'
right = 'right'
strTypeAST = ['id', 's']
strTypePython = 'str'
tupleAST = 'elts'
verifyFuncName = 'verify'
