"""Type stubs for charm.core.math.pairing C extension module."""

from typing import overload

# Module-level constants (group types)
ZR: int
G1: int
G2: int
GT: int

class Pairing:
    """Pairing group context for bilinear pairings."""

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, params: str) -> None: ...
    @overload
    def __init__(self, params: bytes) -> None: ...

class Element:
    """Element in a pairing-based group (ZR, G1, G2, or GT)."""

    type: int
    initialized: int
    preproc: int

    def __init__(self) -> None: ...
    def initPP(self) -> None: ...
    def set(self, value: int | Element) -> int: ...

    # Arithmetic operations
    def __add__(self, other: Element) -> Element: ...
    def __radd__(self, other: Element) -> Element: ...
    def __sub__(self, other: Element) -> Element: ...
    def __rsub__(self, other: Element) -> Element: ...
    def __mul__(self, other: Element) -> Element: ...
    def __rmul__(self, other: Element) -> Element: ...
    def __pow__(self, other: Element | int) -> Element: ...
    def __rpow__(self, other: Element | int) -> Element: ...
    def __neg__(self) -> Element: ...
    def __invert__(self) -> Element: ...

    # Comparison operations
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Element) -> bool: ...
    def __le__(self, other: Element) -> bool: ...
    def __gt__(self, other: Element) -> bool: ...
    def __ge__(self, other: Element) -> bool: ...

    # Conversion and hashing
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...

# Module-level functions
@overload
def init(group: Pairing, type: int) -> Element: ...
@overload
def init(group: Pairing, type: int, value: int) -> Element: ...

def pair(g1: Element, g2: Element) -> Element: ...
def hashPair(element: Element) -> bytes: ...
def H(group: Pairing, data: bytes | str, type: int) -> Element: ...
def random(group: Pairing, type: int) -> Element: ...
def serialize(element: Element) -> bytes: ...
def deserialize(group: Pairing, data: bytes, type: int) -> Element: ...
def ismember(element: Element) -> bool: ...

