from charm.toolbox.paddingschemes import PKCS7Padding
from charm.toolbox.securerandom import OpenSSLRand
from charm.core.crypto.cryptobase import MODE_CBC,AES,selectPRP
from charm.core.crypto.cryptobase import MODE_ECB as _MODE_ECB_RAW
from hashlib import sha256 as sha2
import json
import hmac
import os
import warnings
from base64 import b64encode, b64decode


def _get_mode_ecb():
    """Return MODE_ECB value with a deprecation warning.

    ECB mode is insecure: identical plaintext blocks produce identical
    ciphertext blocks, revealing patterns. Use MODE_CBC or MODE_CTR instead.
    """
    warnings.warn(
        "ECB mode is insecure and should not be used for encryption. "
        "Identical plaintext blocks produce identical ciphertext, revealing patterns. "
        "Use MODE_CBC or MODE_CTR instead.",
        DeprecationWarning,
        stacklevel=2
    )
    return _MODE_ECB_RAW

class MessageAuthenticator(object):
    """ Abstraction for constructing and verifying authenticated messages

        A large number of the schemes can only encrypt group elements
        and do not provide an efficient mechanism for encoding byte in
        those elements. As such we don't pick a symmetric key and encrypt
        it asymmetrically. Rather, we hash a random group element to get the
        symmetric key.

    >>> from charm.toolbox.pairinggroup import PairingGroup,GT,extract_key
    >>> groupObj = PairingGroup('SS512')
    >>> key = groupObj.random(GT)
    >>> m = MessageAuthenticator(extract_key(key))
    >>> AuthenticatedMessage = m.mac('Hello World')
    >>> m.verify(AuthenticatedMessage)
    True
    """
    def __init__(self, key, alg="HMAC_SHA2"):
        """
        Creates a message authenticator and verifier under the specified key
        """
        if alg != "HMAC_SHA2":
            raise ValueError("Currently only HMAC_SHA2 is supported as an algorithm")
        self._algorithm = alg
        self._key = key

    def mac(self, msg, associatedData=b''):
        """
        Authenticates (MAC) a message. The MAC is computed as:
        MAC = HMAC(key, algorithm + associatedData + message).

        Parameters
        ----------
        msg : str or byte str
            The message serving as input to the HMAC algorithm, in addition to the HMAC algorithm and associated data.
        associatedData : str or byte str, optional
            Associated data that will be MACed together with the ciphertext and algorithm; the associated data will not be encrypted.

        Returns
        -------
        dict
            Dictionary composed of the MAC algorithm, the MACed message (or ciphertext), and the digest computed by MACing HMAC_algorithm + associatedData + msg.
        """
        # Ensure the associated data is in byte format, convert if necessary.
        if type(associatedData) != bytes :
            associatedData = bytes(associatedData, "utf-8")
        return {
                "alg": self._algorithm,
                "msg": msg,
                "digest": hmac.new(self._key, bytes(self._algorithm, "utf-8") + associatedData + bytes(msg, "utf-8"), digestmod=sha2).hexdigest()
               }

    def verify(self, msgAndDigest, associatedData=b''):
        """
        Verifies whether the MAC digest from input ciphertext and digest matches the computed one over ciphertext and associated data.

        Parameters
        ----------
        msgAndDigest : dict
            Dictionary composed of the MAC algorithm, the MACed message (or ciphertext), and the digest computed by MACing HMAC_algorithm + associatedData + msg.
            It is the format generated by the mac() function within this class.
        associatedData : str or byte str, optional
            Associated data that will be MACed together with the ciphertext and algorithm; the associated data will not be encrypted.

        Returns
        -------
        bool
            True if the digests match, False otherwise.

        Raises
        ------
        ValueError
            If the HMAC algorithm is not supported.
        """
        if msgAndDigest['alg'] != self._algorithm:
            raise ValueError("Currently only HMAC_SHA2 is supported as an algorithm")
        expected = bytes(self.mac(msgAndDigest['msg'], associatedData=associatedData)['digest'], 'utf-8')
        received = bytes(msgAndDigest['digest'], 'utf-8')
        # Use constant-time comparison to prevent timing attacks
        return hmac.compare_digest(expected, received)

class SymmetricCryptoAbstraction(object):
    """
    Abstraction for symmetric encryption and decryption of data.
    Ideally provide an INDCCA2 secure symmetric container for arbitrary data.
    Currently only supports primitives that JSON can encode and decode.

    A large number of the schemes can only encrypt group elements
    and do not provide an efficient mechanism for encoding byte in
    those elements. As such we don't pick a symmetric key and encrypt
    it asymmetrically. Rather, we hash a random group element to get the
    symmetric key.

    >>> from charm.toolbox.pairinggroup import PairingGroup,GT,extract_key
    >>> groupObj = PairingGroup('SS512')
    >>> a = SymmetricCryptoAbstraction(extract_key(groupObj.random(GT)))
    >>> ct = a.encrypt(b"Friendly Fire Isn't")
    >>> a.decrypt(ct)
    b"Friendly Fire Isn't"
    """

    def __init__(self, key, alg = AES, mode = MODE_CBC):
        self._alg = alg
        self.key_len = 16
        self._block_size = 16
        self._mode = mode
        self._key = key[0:self.key_len] # expected to be bytes
        assert len(self._key) == self.key_len, "SymmetricCryptoAbstraction key too short"
        self._padding = PKCS7Padding()

    def _initCipher(self,IV = None):
        if IV == None :
            IV =  OpenSSLRand().getRandomBytes(self._block_size)
        self._IV = IV
        return selectPRP(self._alg,(self._key,self._mode,self._IV))

    def __encode_decode(self,data,func):
        data['IV'] = func(data['IV'])
        data['CipherText'] = func(data['CipherText'])
        return data

    #This code should be factored out into another class
    #Because json is only defined over strings, we need to base64 encode the encrypted data
    # and convert the base 64 byte array into a utf8 string
    def _encode(self, data):
        return self.__encode_decode(data, lambda x: b64encode(x).decode('utf-8'))

    def _decode(self, data):
        return self.__encode_decode(data, lambda x: b64decode(bytes(x, 'utf-8')))

    def encrypt(self, message):
        #This should be removed when all crypto functions deal with bytes"
        if type(message) != bytes :
            message = bytes(message, "utf-8")
        ct = self._encrypt(message)
        #JSON strings cannot have binary data in them, so we must base64 encode cipher
        cte = json.dumps(self._encode(ct))
        return cte

    def _encrypt(self, message):
        #Because the IV cannot be set after instantiation, decrypt and encrypt
        # must operate on their own instances of the cipher
        cipher = self._initCipher()
        ct= {'ALG': self._alg,
            'MODE': self._mode,
            'IV': self._IV,
            'CipherText': cipher.encrypt(self._padding.encode(message))
            }
        return ct

    def decrypt(self, cipherText):
        f = json.loads(cipherText)
        return self._decrypt(self._decode(f))

    def _decrypt(self, cipherText):
        cipher = self._initCipher(cipherText['IV'])
        msg = cipher.decrypt(cipherText['CipherText'])
        return self._padding.decode(msg)

class AuthenticatedCryptoAbstraction(SymmetricCryptoAbstraction):
    """
    Implements Authenticated Encryption with Associated Data (AEAD) abstraction. The associated data is optional, and this version is backwards compatible
    with the same class without the associated data option.

    Examples
    --------
    >>> from hashlib import sha256
    >>> import charm.toolbox.symcrypto
    >>> key = sha256(b'shameful secret key').digest()
    >>> cipher = charm.toolbox.symcrypto.AuthenticatedCryptoAbstraction(key)
    >>> ciphertext = cipher.encrypt('My age is 42.')
    >>> cipher.decrypt(ciphertext)
    b'My age is 42.'
    >>> ciphertext2 = cipher.encrypt(b'My age is 42.')
    >>> cipher.decrypt(ciphertext2)
    b'My age is 42.'
    >>> ad = b'\x10\x11\x11\x11'
    >>> ciphertextAssociatedData = cipher.encrypt('Some network PDU.', associatedData=ad)
    >>> cipher.decrypt(ciphertextAssociatedData)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "./charm/toolbox/symcrypto.py", line 233, in decrypt
        raise ValueError("Invalid mac. Your data was tampered with or your key is wrong")
    ValueError: Invalid mac. Your data was tampered with or your key is wrong
    >>> cipher.decrypt(ciphertextAssociatedData, associatedData='wrong data')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "./charm/toolbox/symcrypto.py", line 233, in decrypt
        raise ValueError("Invalid mac. Your data was tampered with or your key is wrong")
    ValueError: Invalid mac. Your data was tampered with or your key is wrong
    >>> cipher.decrypt(ciphertextAssociatedData, associatedData=b'\x10\x11\x11\x11')
    b'Some network PDU.'
    >>>
    """
    def encrypt(self, msg, associatedData=''):
        """
        Encrypts a message in AEAD mode (Authenticated Encryption with Associated Data) using the superclass symmetric encryption parameters.
        The MAC is computed with both the ciphertext and associated data (and other cryptosystem parameters), but the associated data is not encrypted, nor
        saved within the ciphertext structure.

        Parameters
        ----------
        msg : str or byte str
            The message to be encrypted.
        associatedData : str or byte str, optional
            Associated data that will be MACed together with the ciphertext and algorithm; the associated data will not be encrypted.

        Returns
        -------
        dict
            Dictionary structure containing:
                msg: {'ALG': symmetric cryptosystem.
                      'MODE': symmetric encryption mode.
                      'IV': the IV for the encryption algorithm.
                      'CipherText': the padded ciphertext (padding according to PKCS 7).
                     }
                "alg": The HMAC algorithm.
                "digest": The MAC computed as MAC = HMAC(key, alg + associatedData + msg)

        Notes
        -----
        The IV is included in the computation of the MAC. In fact, all cipher parameters are included: the encryption function returns a JSON object from
        a dictionary composed of the cipher parameters (e.g., algorithm, mode, IV), and the ciphertext. The MAC function uses the whole JSON object/string
        to compute the MAC, prepended with the HMAC algorithm + associatedData.

        The MAC key is derived using HMAC-based key separation.
        """
        mac_key = hmac.new(self._key, b'charm-mac-key-v1', sha2).digest()
        mac = MessageAuthenticator(mac_key)
        enc = super(AuthenticatedCryptoAbstraction, self).encrypt(msg)
        return mac.mac(enc, associatedData=associatedData)

    def decrypt(self, cipherText, associatedData=''):
        """
        Decrypts a ciphertext in AEAD mode (Authenticated Encryption with Associated Data) using the superclass symmetric encryption parameters.
        The MAC is computed with both the ciphertext and associated data (and other cryptosystem parameters), but the associated data is not encrypted, nor
        available within the ciphertext structure.

        Parameters
        ----------
        ciphertext : str or byte str
            The message to be decrypted.
        associatedData : str or byte str, optional
            Associated data that will be MACed together with the ciphertext and algorithm. This associated text must be in plaintext.

        Returns
        -------
        byte str
            The decrypted plaintext, if the ciphertext was successfuly authenticated. Raise exception otherwise.

        Raises
        ------
        ValueError
            If the MAC is invalid.

        Notes
        -----
        The IV is included in the computation of the MAC. In fact, all cipher parameters are included: the encryption function returns a JSON object from
        a dictionary composed of the cipher parameters (e.g., algorithm, mode, IV), and the ciphertext. The MAC function uses the whole JSON object/string
        to compute the MAC, prepended with the HMAC algorithm + associatedData.

        The MAC key is derived using HMAC-based key separation.
        """
        mac_key = hmac.new(self._key, b'charm-mac-key-v1', sha2).digest()
        mac = MessageAuthenticator(mac_key)
        if not mac.verify(cipherText, associatedData=associatedData):
            raise ValueError("Invalid mac. Your data was tampered with or your key is wrong")
        else:
            return super(AuthenticatedCryptoAbstraction, self).decrypt(cipherText['msg'])


class AESGCMCryptoAbstraction(object):
    """
    Authenticated Encryption using AES-GCM (Galois/Counter Mode).

    Provides IND-CCA2 secure authenticated encryption with associated data (AEAD)
    using AES-GCM via Charm's native OpenSSL-based C extension. This is the
    recommended symmetric encryption abstraction for new code — it replaces the
    Encrypt-then-MAC construction in AuthenticatedCryptoAbstraction with a
    single-pass AEAD cipher.

    No external Python dependencies are required; the underlying implementation
    uses OpenSSL's EVP API directly through charm.core.crypto.AES_GCM.

    Examples
    --------
    >>> from hashlib import sha256
    >>> import charm.toolbox.symcrypto
    >>> key = sha256(b'shameful secret key').digest()[:16]
    >>> cipher = charm.toolbox.symcrypto.AESGCMCryptoAbstraction(key)
    >>> ciphertext = cipher.encrypt(b'My age is 42.')
    >>> cipher.decrypt(ciphertext)
    b'My age is 42.'
    >>> ad = b'\\x10\\x11\\x11\\x11'
    >>> ct_ad = cipher.encrypt(b'Network PDU.', associatedData=ad)
    >>> cipher.decrypt(ct_ad, associatedData=ad)
    b'Network PDU.'
    >>> cipher.decrypt(ct_ad, associatedData=b'wrong')
    Traceback (most recent call last):
        ...
    ValueError: Decryption failed: authentication tag is invalid (data tampered or wrong key)
    """

    # NIST recommends 96-bit (12-byte) nonces for AES-GCM
    _NONCE_SIZE = 12
    # AES-GCM produces a 128-bit (16-byte) authentication tag
    _TAG_SIZE = 16

    def __init__(self, key):
        """
        Create an AES-GCM encryption/decryption object.

        Parameters
        ----------
        key : bytes
            AES key — must be 16 (AES-128), 24 (AES-192), or 32 (AES-256) bytes.

        Raises
        ------
        ValueError
            If the key length is not 16, 24, or 32 bytes.
        """
        if len(key) not in (16, 24, 32):
            raise ValueError(
                f"AES-GCM key must be 16, 24, or 32 bytes, got {len(key)}"
            )
        self._key = key

    def encrypt(self, message, associatedData=b''):
        """
        Encrypt a message with AES-GCM.

        Parameters
        ----------
        message : bytes or str
            The plaintext to encrypt.
        associatedData : bytes or str, optional
            Associated data authenticated but not encrypted.

        Returns
        -------
        str
            JSON-encoded ciphertext containing nonce, ciphertext+tag, and mode.
        """
        from charm.core.crypto.AES_GCM import encrypt as _gcm_encrypt

        if isinstance(message, str):
            message = message.encode('utf-8')
        if isinstance(associatedData, str):
            associatedData = associatedData.encode('utf-8')

        nonce = os.urandom(self._NONCE_SIZE)
        ct_and_tag = _gcm_encrypt(self._key, message, nonce,
                                   aad=associatedData or b'')

        payload = {
            'ALG': 'AES-GCM',
            'Nonce': b64encode(nonce).decode('utf-8'),
            'CipherText': b64encode(ct_and_tag).decode('utf-8'),
        }
        return json.dumps(payload)

    def decrypt(self, cipherText, associatedData=b''):
        """
        Decrypt and authenticate an AES-GCM ciphertext.

        Parameters
        ----------
        cipherText : str
            JSON-encoded ciphertext from encrypt().
        associatedData : bytes or str, optional
            Associated data that was provided during encryption.

        Returns
        -------
        bytes
            The decrypted plaintext.

        Raises
        ------
        ValueError
            If authentication fails (data tampered or wrong key/AD).
        """
        from charm.core.crypto.AES_GCM import decrypt as _gcm_decrypt

        if isinstance(associatedData, str):
            associatedData = associatedData.encode('utf-8')

        payload = json.loads(cipherText)
        nonce = b64decode(payload['Nonce'])
        ct_and_tag = b64decode(payload['CipherText'])

        try:
            plaintext = _gcm_decrypt(self._key, ct_and_tag, nonce,
                                      aad=associatedData or b'')
        except Exception:
            raise ValueError(
                "Decryption failed: authentication tag is invalid "
                "(data tampered or wrong key)"
            )
        return plaintext
